apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels: #match selector wich connects the pods to this deployment resource
      app: my-pod
  template: #defines the pod that it will be deploying.
    metadata:
      labels:
        app: my-pod
    spec:
      containers:
        - name: my-pod
          image: httpd:latest
          ports:
            - containerPort: 80
