apiVersion: batch/v1
kind: CronJob
metadata:
  name: batch-job
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: batch-job
              image: busybox
              command: ["echo", "Hello from the kubernetes cluster!"]
          restartPolicy: OnFailure
