apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-deployment
  labels:
    app: secret-deployment
spec:
  replicas: 2
  selector:
    matchLabels: #match selector wich connects the pods to this deployment resource
      app: secret-pod
  template: #defines the pod that it will be deploying.
    metadata:
      labels:
        app: secret-pod
    spec:
      containers:
        - name: secret-pod
          image: httpd:2
          env:
            - name: app-secret
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: secretValue
          ports:
            - containerPort: 80
